<?php

namespace Database\Seeders;

use App\Models\Gift;
use Illuminate\Database\Seeder;

class GiftSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gifts = [
            [
                'name' => 'باقة ورود حمراء رومانسية',
                'description' => 'باقة رائعة من الورود الحمراء الطازجة مع تغليف أنيق، مثالية للتعبير عن الحب والرومانسية في المناسبات الخاصة.',
                'price' => 150.00,
                'category' => 'valentine',
                'occasion' => 'عيد الحب',
                'images' => ['/images/gifts/red-roses.jpg'],
                'size' => 'medium',
                'is_customizable' => true,
                'customization_options' => ['رسالة شخصية', 'لون التغليف', 'إضافة شوكولاتة'],
                'stock_quantity' => 25,
                'is_featured' => true,
                'delivery_time' => 'نفس اليوم',
                'rating' => 4.8,
                'reviews_count' => 42,
            ],
            [
                'name' => 'صندوق شوكولاتة فاخر',
                'description' => 'مجموعة مختارة من أفخر أنواع الشوكولاتة البلجيكية في صندوق أنيق، هدية مثالية لعشاق الحلويات.',
                'price' => 120.00,
                'category' => 'birthday',
                'occasion' => 'عيد ميلاد',
                'images' => ['/images/gifts/chocolate-box.jpg'],
                'size' => 'small',
                'is_customizable' => true,
                'customization_options' => ['نوع الشوكولاتة', 'رسالة على الصندوق'],
                'stock_quantity' => 30,
                'is_featured' => true,
                'delivery_time' => 'خلال 24 ساعة',
                'rating' => 4.9,
                'reviews_count' => 67,
            ],
            [
                'name' => 'سلة فواكه طازجة',
                'description' => 'سلة مليئة بأطيب وأجود أنواع الفواكه الطازجة والموسمية، مرتبة بشكل جميل ومغلفة بأناقة.',
                'price' => 80.00,
                'category' => 'general',
                'occasion' => 'زيارة',
                'images' => ['/images/gifts/fruit-basket.jpg'],
                'size' => 'large',
                'is_customizable' => false,
                'stock_quantity' => 20,
                'is_featured' => false,
                'delivery_time' => 'نفس اليوم',
                'rating' => 4.5,
                'reviews_count' => 28,
            ],
            [
                'name' => 'دبدوب عملاق مع قلب',
                'description' => 'دبدوب ناعم وكبير الحجم يحمل قلباً أحمر، هدية رائعة للأطفال والأحباب في المناسبات الرومانسية.',
                'price' => 200.00,
                'category' => 'valentine',
                'occasion' => 'عيد الحب',
                'images' => ['/images/gifts/teddy-bear.jpg'],
                'size' => 'large',
                'is_customizable' => true,
                'customization_options' => ['لون الدبدوب', 'رسالة على القلب'],
                'stock_quantity' => 15,
                'is_featured' => true,
                'delivery_time' => 'خلال 24 ساعة',
                'rating' => 4.7,
                'reviews_count' => 35,
            ],
            [
                'name' => 'مجموعة عطور فاخرة',
                'description' => 'مجموعة من العطور الفاخرة في عبوات أنيقة، تشمل عطور رجالية ونسائية من أفضل الماركات العالمية.',
                'price' => 350.00,
                'category' => 'anniversary',
                'occasion' => 'ذكرى زواج',
                'images' => ['/images/gifts/perfume-set.jpg'],
                'size' => 'medium',
                'is_customizable' => true,
                'customization_options' => ['نوع العطر', 'تغليف خاص'],
                'stock_quantity' => 12,
                'is_featured' => true,
                'delivery_time' => 'خلال 48 ساعة',
                'rating' => 4.9,
                'reviews_count' => 23,
            ],
            [
                'name' => 'كيكة عيد ميلاد مخصصة',
                'description' => 'كيكة عيد ميلاد مصنوعة خصيصاً حسب الطلب، بنكهات متنوعة وتصميم مخصص حسب المناسبة.',
                'price' => 180.00,
                'category' => 'birthday',
                'occasion' => 'عيد ميلاد',
                'images' => ['/images/gifts/birthday-cake.jpg'],
                'size' => 'medium',
                'is_customizable' => true,
                'customization_options' => ['النكهة', 'التصميم', 'الكتابة على الكيكة'],
                'stock_quantity' => 0, // Out of stock
                'is_featured' => false,
                'delivery_time' => 'خلال 24 ساعة',
                'rating' => 4.6,
                'reviews_count' => 51,
            ],
            [
                'name' => 'مجموعة ألعاب تعليمية للأطفال',
                'description' => 'مجموعة متنوعة من الألعاب التعليمية المناسبة للأطفال، تساعد على تنمية المهارات والإبداع.',
                'price' => 95.00,
                'category' => 'baby',
                'occasion' => 'مولود جديد',
                'images' => ['/images/gifts/educational-toys.jpg'],
                'size' => 'medium',
                'is_customizable' => false,
                'stock_quantity' => 18,
                'is_featured' => false,
                'delivery_time' => 'خلال 24 ساعة',
                'rating' => 4.4,
                'reviews_count' => 19,
            ],
            [
                'name' => 'باقة زهور مختلطة',
                'description' => 'باقة جميلة من الزهور المختلطة بألوان زاهية، مناسبة لجميع المناسبات السعيدة.',
                'price' => 110.00,
                'category' => 'general',
                'occasion' => 'تهنئة',
                'images' => ['/images/gifts/mixed-flowers.jpg'],
                'size' => 'medium',
                'is_customizable' => true,
                'customization_options' => ['أنواع الزهور', 'لون التغليف'],
                'stock_quantity' => 22,
                'is_featured' => false,
                'delivery_time' => 'نفس اليوم',
                'rating' => 4.3,
                'reviews_count' => 31,
            ],
            [
                'name' => 'مجموعة قرطاسية فاخرة',
                'description' => 'مجموعة أنيقة من القرطاسية الفاخرة تشمل دفاتر وأقلام مميزة، مثالية لطلاب الجامعة.',
                'price' => 75.00,
                'category' => 'graduation',
                'occasion' => 'تخرج',
                'images' => ['/images/gifts/stationery-set.jpg'],
                'size' => 'small',
                'is_customizable' => true,
                'customization_options' => ['اللون', 'النقش الشخصي'],
                'stock_quantity' => 35,
                'is_featured' => false,
                'delivery_time' => 'خلال 24 ساعة',
                'rating' => 4.2,
                'reviews_count' => 14,
            ],
            [
                'name' => 'سلة هدايا العيد',
                'description' => 'سلة مليئة بالحلويات والمكسرات والتمور الفاخرة، مثالية لتهنئة العيد ومشاركة الفرحة.',
                'price' => 160.00,
                'category' => 'eid',
                'occasion' => 'عيد الفطر',
                'images' => ['/images/gifts/eid-basket.jpg'],
                'size' => 'large',
                'is_customizable' => true,
                'customization_options' => ['محتويات السلة', 'بطاقة تهنئة'],
                'stock_quantity' => 28,
                'is_featured' => true,
                'delivery_time' => 'نفس اليوم',
                'rating' => 4.8,
                'reviews_count' => 45,
            ],
        ];

        foreach ($gifts as $gift) {
            Gift::create($gift);
        }
    }
}
