<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>System Report - {{ config('app.name') }}</title>
    <!-- fav icon -->
        <link rel="icon" type="image/png" href="/images/fav_icon.png">
    <style>
        body {
            font-family: "El Messiri", sans-serif;
            font-size: 12px;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #7f8c8d;
        }
        .section {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .metric-row {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #eee;
        }
        .metric-label {
            font-weight: bold;
            color: #555;
        }
        .metric-value {
            color: #2c3e50;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #7f8c8d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name', 'Tulip Store') }}</h1>
        <p>Complete System Report</p>
        <p>Generated: {{ $generated_at }}</p>
        <p>Generated By: {{ $generated_by }}</p>
    </div>

    <div class="section">
        <div class="section-title">System Overview</div>
        <div class="metric-row">
            <span class="metric-label">Total Users:</span>
            <span class="metric-value">{{ number_format($users_count) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Orders:</span>
            <span class="metric-value">{{ number_format($orders_count) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Products:</span>
            <span class="metric-value">{{ number_format($products_count) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Stores:</span>
            <span class="metric-value">{{ number_format($stores_count) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Employees:</span>
            <span class="metric-value">{{ number_format($employees_count) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Transactions:</span>
            <span class="metric-value">{{ number_format($transactions_count) }}</span>
        </div>
    </div>

    @if(isset($summary))
    <div class="section">
        <div class="section-title">Financial Summary</div>
        <div class="metric-row">
            <span class="metric-label">Total Revenue:</span>
            <span class="metric-value">${{ number_format($summary['total_revenue'] ?? 0, 2) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Monthly Revenue:</span>
            <span class="metric-value">${{ number_format($summary['monthly_revenue'] ?? 0, 2) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Total Commission:</span>
            <span class="metric-value">${{ number_format($summary['total_commission'] ?? 0, 2) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Monthly Commission:</span>
            <span class="metric-value">${{ number_format($summary['monthly_commission'] ?? 0, 2) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Average Order Value:</span>
            <span class="metric-value">${{ number_format($summary['avg_order_value'] ?? 0, 2) }}</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Platform Metrics</div>
        <div class="metric-row">
            <span class="metric-label">Active Users:</span>
            <span class="metric-value">{{ number_format($summary['active_users'] ?? 0) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Active Stores:</span>
            <span class="metric-value">{{ number_format($summary['active_stores'] ?? 0) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Active Products:</span>
            <span class="metric-value">{{ number_format($summary['active_products'] ?? 0) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Pending Orders:</span>
            <span class="metric-value">{{ number_format($summary['pending_orders'] ?? 0) }}</span>
        </div>
        <div class="metric-row">
            <span class="metric-label">Low Stock Alerts:</span>
            <span class="metric-value">{{ number_format($summary['low_stock_alerts'] ?? 0) }}</span>
        </div>
    </div>
    @endif

    <div class="footer">
        <p>This is an automated system report generated on {{ $generated_at }}</p>
        <p>Confidential - For Internal Use Only</p>
    </div>
</body>
</html>

